# Generated by Django 3.2.7 on 2021-10-06 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.model_utility
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('on_board_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'USER_CREATED'), (2, 'PASSWORD_SET'), (4, 'USER_REVIEWED'), (3, 'IN_PROGRESS'), (5, 'COMPLETED'), (6, 'REJECTED')], null=True)),
                ('is_user_onboard', models.BooleanField(default=False)),
                ('slug_value', models.SlugField(blank=True, null=True, unique=True)),
                ('user_role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ADMIN'), (2, 'SME'), (3, 'SUPPLIER'), (4, 'FACTOR')], null=True)),
                ('credit_limit', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('currency_value', models.CharField(default='USD', max_length=5)),
                ('is_deleted', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_detail_path', models.CharField(default='', help_text='Base path for instance files', max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('company_registered_address', models.TextField()),
                ('company_physical_address', models.TextField(max_length=200)),
                ('company_registration_id', models.CharField(max_length=200)),
                ('company_website', models.URLField()),
                ('company_telephone_number', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_person_designation', models.CharField(max_length=100)),
                ('contact_mobile_phone', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=200)),
                ('no_full_time_employees', models.IntegerField(blank=True, default=0, help_text='Number of full time employees')),
                ('last_fy_annual_revenue', models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Last FY years Annual Revenue', max_digits=20)),
                ('total_debt_amounts', models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Total Amount of Debt on the Books', max_digits=20)),
                ('inventory_on_hand', models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Inventory on Hand (COGS approx)', max_digits=20)),
                ('current_balance_sheet', models.FileField(blank=True, help_text='Current balance sheet', upload_to=utils.model_utility.user_detail_base_path)),
                ('last_year_account_statement', models.FileField(blank=True, help_text='Last year account statement', upload_to=utils.model_utility.user_detail_base_path)),
                ('last_year_profit_loss', models.FileField(blank=True, help_text='Last 12 months profit/loss', upload_to=utils.model_utility.user_detail_base_path)),
                ('last_years_annual_reports', models.FileField(blank=True, help_text='Last years annual reports', upload_to=utils.model_utility.user_detail_base_path)),
                ('ytd_management_accounts', models.FileField(blank=True, help_text='YTD management accounts', upload_to=utils.model_utility.user_detail_base_path)),
                ('last_bank_statements', models.FileField(blank=True, help_text='Last 3 months Bank statements', upload_to=utils.model_utility.user_detail_base_path)),
                ('directors_address_proof', models.FileField(blank=True, help_text='Directors Proof of address within 3 months', upload_to=utils.model_utility.user_detail_base_path)),
                ('share_holding_corporate_structure', models.FileField(blank=True, help_text='Shareholding / Corporate Structure', upload_to=utils.model_utility.user_detail_base_path)),
                ('cap_table', models.FileField(blank=True, help_text='Cap table', upload_to=utils.model_utility.user_detail_base_path)),
                ('trade_cycle_po', models.FileField(blank=True, help_text='PO', upload_to=utils.model_utility.user_detail_base_path)),
                ('trade_cycle_invoice', models.FileField(blank=True, help_text='Invoice', upload_to=utils.model_utility.user_detail_base_path)),
                ('trade_cycle_bl', models.FileField(blank=True, help_text='BL', upload_to=utils.model_utility.user_detail_base_path)),
                ('trade_cycle_awb', models.FileField(blank=True, help_text='AWB', upload_to=utils.model_utility.user_detail_base_path)),
                ('trade_cycle_packing_list', models.FileField(blank=True, help_text='Packing list', upload_to=utils.model_utility.user_detail_base_path)),
                ('trade_cycle_sgs_report', models.FileField(blank=True, help_text='SGS report', upload_to=utils.model_utility.user_detail_base_path)),
                ('date_created', models.DateField(null=True)),
                ('date_modified', models.DateField(null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserDetailFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_file_key', models.CharField(help_text='id type eg: Passport, Driving licence etc', max_length=50)),
                ('detail_id_file', models.FileField(upload_to=utils.model_utility.user_detail_id_base_path)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_id_files', to='registration.userdetailmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LoginTrackerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_value', models.IntegerField(default=777777)),
                ('otp_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'OTP_SENT'), (2, 'OTP_VERIFIED')], null=True)),
                ('otp_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_session_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='on_boarding_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_details', to='registration.userdetailmodel'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
