# Generated by Django 3.2.3 on 2021-11-01 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0005_auto_20211101_0354'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='master_contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sme_master_contract', to='transaction_app.contractmodel'),
        ),
    ]
