# Generated by Django 3.2.3 on 2021-11-05 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0008_fundinvoicemodel_contract_category'),
        ('registration', '0002_user_master_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='master_contract',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sme_master_contract', to='transaction_app.contractmodel'),
        ),
    ]
