# Generated by Django 3.2.3 on 2021-11-15 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.model_utility


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_user_master_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_sheet', models.FileField(blank=True, help_text='Balance sheet', upload_to=utils.model_utility.xero_file_path)),
                ('account_statement', models.FileField(blank=True, help_text='Account statement', upload_to=utils.model_utility.xero_file_path)),
                ('profit_loss', models.FileField(blank=True, help_text='Profit/loss', upload_to=utils.model_utility.xero_file_path)),
                ('date_created', models.DateField(null=True)),
                ('date_modified', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_xero_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XeroAuthTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=5000)),
                ('refresh_token', models.CharField(max_length=5000)),
                ('date_created', models.DateField(null=True)),
                ('date_modified', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_xero_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
