# Generated by Django 3.2.3 on 2021-12-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20211201_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_xero_files_added',
        ),
    ]
