# Generated by Django 3.2.3 on 2022-02-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_remove_user_is_xero_files_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailmodel',
            name='additional_info',
            field=models.JSONField(null=True),
        ),
    ]
