# Generated by Django 3.2.3 on 2022-02-21 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_onboardemaildata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=100, null=True)),
                ('contact_person_designation', models.CharField(max_length=100, null=True)),
                ('contact_mobile_phone', models.CharField(max_length=200, null=True)),
                ('contact_email', models.EmailField(max_length=200, null=True)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_id_contact', to='registration.userdetailmodel')),
            ],
        ),
    ]
