# Generated by Django 3.2.3 on 2022-04-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20220420_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailmodel',
            name='inventory_on_hand',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Inventory on Hand (COGS approx)', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdetailmodel',
            name='last_fy_annual_revenue',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Last FY years Annual Revenue', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdetailmodel',
            name='total_debt_amounts',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Total Amount of Debt on the Books', max_digits=20, null=True),
        ),
    ]
