# Generated by Django 3.2.3 on 2022-05-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20220426_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_reset_password',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
