# Generated by Django 3.2.3 on 2022-05-19 12:43

from django.db import migrations, models
import utils.model_utility


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.model_utility.profile_image_path),
        ),
    ]
