# Generated by Django 3.2.3 on 2022-06-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mail_send',
            field=models.BooleanField(default=False),
        ),
    ]
