# Generated by Django 3.2.3 on 2022-06-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_user_is_mail_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
