# Generated by Django 3.2.3 on 2022-06-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_user_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default='2022-05-30'),
            preserve_default=False,
        ),
    ]
