# Generated by Django 3.2.7 on 2021-10-06 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import utils.model_utility


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_conditions', models.TextField(null=True)),
                ('fixed_fee_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('total_sales_amount', models.DecimalField(decimal_places=3, max_digits=20)),
                ('contract_number', models.CharField(blank=True, max_length=50)),
                ('date_created', models.DateField(null=True)),
                ('date_modified', models.DateField(null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FundInvoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('invoice_number', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('shipment_date', models.DateField(blank=True, null=True)),
                ('currency_used', models.CharField(default='USD', max_length=5)),
                ('assign_to', models.CharField(blank=True, max_length=20)),
                ('application_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'IN_PROGRESS'), (2, 'COMPLETED'), (3, 'REJECTED')], null=True)),
                ('transport_mode', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'AIR'), (2, 'SEA'), (3, 'MIXED')], null=True)),
                ('destination_country', django_countries.fields.CountryField(max_length=2)),
                ('date_created', models.DateField(null=True)),
                ('date_modified', models.DateField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_invoice_sme', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_invoice_supplier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paying_amount', models.DecimalField(decimal_places=3, max_digits=20)),
                ('payment_method', models.PositiveSmallIntegerField(choices=[(1, 'BANK_TRANSFER'), (2, 'ONLINE_TRANSFER')])),
                ('payment_ref_number', models.CharField(max_length=50)),
                ('payment_remarks', models.TextField()),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(1, 'PAYMENT_TO_FACTORING_COMPANY_BY_SME'), (2, 'PAYMENT_TO_SUPPLIER_BY_ADMIN'), (3, 'PAYMENT_TO_ADMIN_BY_FACTORING_COMPANY')])),
                ('acknowledgement_status', models.PositiveSmallIntegerField(choices=[(1, 'ACKNOWLEDGED'), (2, 'ACKNOWLEDGED_BY_ADMIN'), (3, 'ACKNOWLEDGED_BY_FACTOR'), (4, 'PENDING'), (5, 'PAID')])),
                ('acknowledgement_completed', models.BooleanField(default=False)),
                ('is_adhoc', models.BooleanField(default=False)),
                ('tax_amount', models.DecimalField(decimal_places=3, max_digits=20)),
                ('term_order', models.IntegerField(default=1)),
                ('system_remarks', models.TextField(blank=True)),
                ('date_created', models.DateField(null=True)),
                ('date_modified', models.DateField(null=True)),
                ('fund_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_fund_invoice', to='transaction_app.fundinvoicemodel')),
                ('payment_made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTermModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
                ('date_created', models.DateField(null=True)),
                ('date_modified', models.DateField(null=True)),
                ('for_sme', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierTermsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_label', models.CharField(max_length=100)),
                ('terms_order', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'PERCENTAGE'), (2, 'AMOUNT'), (3, 'BALANCE')], null=True)),
                ('before_shipment', models.BooleanField(default=True)),
                ('payment_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_terms', to='transaction_app.paymenttermmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SmeTermsInstallmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField()),
                ('period', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'WEEKLY'), (2, 'MONTHLY')], null=True)),
                ('equal_installments', models.BooleanField(default=True)),
                ('payment_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sme_installment_terms', to='transaction_app.paymenttermmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SmeTermsAmountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_label', models.CharField(max_length=200)),
                ('terms_order', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'PERCENTAGE'), (2, 'AMOUNT'), (3, 'BALANCE')], null=True)),
                ('days', models.IntegerField()),
                ('criteria', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'DAYS_FROM_CONTRACT_SIGNATURE'), (2, 'DAYS_FROM_LAST_PAYMENT')], null=True)),
                ('payment_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sme_amount_terms', to='transaction_app.paymenttermmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SignedContractFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_doc_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'GENERATED_CONTRACT'), (2, 'SME_SIGNED_CONTRACT'), (3, 'ADMIN_SIGNED_CONTRACT')], null=True)),
                ('file_path', models.CharField(blank=True, max_length=150)),
                ('file_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'CREATED'), (2, 'OBSOLETE'), (3, 'ACTIVE')], null=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_by', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_contract_file', to='transaction_app.contractmodel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_date', models.DateField(blank=True, null=True)),
                ('number_of_shipments', models.IntegerField()),
                ('other_info', models.CharField(blank=True, max_length=200)),
                ('system_remarks', models.TextField(blank=True)),
                ('date_created', models.DateField(null=True)),
                ('date_modified', models.DateField(null=True)),
                ('fund_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_fund_invoice', to='transaction_app.fundinvoicemodel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.IntegerField()),
                ('document_type', models.CharField(choices=[(1, 'INVOICE'), (2, 'BL'), (3, 'AWB'), (4, 'PACKING_LIST'), (5, 'SGS_REPORT')], default=1, max_length=200)),
                ('file_object', models.FileField(upload_to=utils.model_utility.shipment_file_path)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_action_by', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_files', to='transaction_app.shipmentmodel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_created_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('action_taken', models.PositiveSmallIntegerField(choices=[(1, 'PAYMENT_ADDED'), (2, 'PAYMENT_RECEIVED_ACKNOWLEDGED'), (3, 'PAYMENT_ON_HOLD_ACKNOWLEDGED')])),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_action_by', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_status_data', to='transaction_app.paymentmodel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_file', models.FileField(upload_to=utils.model_utility.payment_file_path)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_files', to='transaction_app.paymentmodel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FundInvoiceStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_created_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('action_taken', models.CharField(blank=True, max_length=100)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_action_by', to=settings.AUTH_USER_MODEL)),
                ('fund_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_invoice_status', to='transaction_app.fundinvoicemodel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='fundinvoicemodel',
            name='supplier_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_supplier_terms', to='transaction_app.paymenttermmodel'),
        ),
        migrations.CreateModel(
            name='FundInvoiceFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_object', models.FileField(upload_to=utils.model_utility.fund_invoice_files_path)),
                ('fund_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_invoice_files', to='transaction_app.fundinvoicemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ContractTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('gross_margin', models.DecimalField(decimal_places=3, max_digits=6)),
                ('markup', models.DecimalField(decimal_places=3, max_digits=6)),
                ('fixed_fee_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'PERCENTAGE'), (2, 'AMOUNT'), (3, 'BALANCE')], null=True)),
                ('fixed_fee_value', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('status', models.BooleanField(default=True)),
                ('date_created', models.DateField(null=True)),
                ('date_modified', models.DateField(null=True)),
                ('payment_terms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_terms', to='transaction_app.paymenttermmodel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ContractSupportingDocsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_file', models.FileField(upload_to=utils.model_utility.contract_file_base_path)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_docs', to='transaction_app.contractmodel')),
            ],
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='contract_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_type', to='transaction_app.contracttypemodel'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='factoring_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_factoring_company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='fund_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_fund_invoice', to='transaction_app.fundinvoicemodel'),
        ),
        migrations.CreateModel(
            name='AdditionalShipmentFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_shipment_file', models.FileField(upload_to=utils.model_utility.additional_shipment_file_path)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_by', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_shipment_files', to='transaction_app.shipmentmodel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
