# Generated by Django 3.2.3 on 2021-10-06 07:43

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0002_remove_fundinvoicemodel_destination_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinvoicemodel',
            name='destination_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
