# Generated by Django 3.2.3 on 2021-11-01 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction_app', '0004_alter_fundinvoicemodel_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='is_master_contract',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='factoring_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_factoring_company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='fund_invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_fund_invoice', to='transaction_app.fundinvoicemodel'),
        ),
        migrations.CreateModel(
            name='MasterContractStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_created_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('action_taken', models.CharField(blank=True, max_length=100)),
                ('assign_to', models.CharField(blank=True, max_length=20)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_by_user', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_contract_status', to='transaction_app.contractmodel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
