# Generated by Django 3.2.3 on 2021-11-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0005_auto_20211101_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='is_master_contract',
            field=models.BooleanField(default=False),
        ),
    ]
