
# Generated by Django 3.2.3 on 2021-11-03 13:19
# Generated by Django 3.2.7 on 2021-11-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0007_alter_contractmodel_total_sales_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinvoicemodel',
            name='contract_category',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'NEW_CONTRACT'), (2, 'MASTER_CONTRACT')], null=True),
        ),
    ]
