# Generated by Django 3.2.3 on 2021-11-05 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0008_fundinvoicemodel_contract_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigningRemainderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_time', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sme_remainder_contract', to='transaction_app.contractmodel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
