# Generated by Django 3.2.3 on 2021-11-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0009_signingremaindermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractmodel',
            name='total_sales_amount',
        ),
        migrations.AddField(
            model_name='fundinvoicemodel',
            name='total_sales_amount',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
    ]
