# Generated by Django 3.2.3 on 2021-11-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0010_auto_20211109_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinvoicemodel',
            name='fixed_fee_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
