# Generated by Django 3.2.3 on 2021-11-12 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction_app', '0012_contractmodel_total_sales_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinvoicemodel',
            name='factoring_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_factoring_company', to=settings.AUTH_USER_MODEL),
        ),
    ]
