# Generated by Django 3.2.3 on 2021-11-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0013_fundinvoicemodel_factoring_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='signedcontractfilesmodel',
            name='remainder_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='signedcontractfilesmodel',
            name='remainder_sending_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='SigningRemainderModel',
        ),
    ]
