# Generated by Django 3.2.3 on 2021-11-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0014_auto_20211118_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=100)),
                ('sort_code', models.CharField(max_length=50)),
                ('sterling', models.CharField(max_length=50, null=True)),
                ('euros', models.CharField(max_length=50, null=True)),
                ('us_dollar', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
