# Generated by Django 3.2.3 on 2021-11-25 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0015_accountdetailsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signedcontractfilesmodel',
            old_name='remainder_count',
            new_name='reminder_count',
        ),
        migrations.RenameField(
            model_name='signedcontractfilesmodel',
            old_name='remainder_sending_time',
            new_name='reminder_sending_time',
        ),
    ]
