# Generated by Django 3.2.3 on 2022-01-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0017_auto_20220105_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='gross_margin',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='markup',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
    ]
