# Generated by Django 3.2.3 on 2022-01-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0019_paymenttermmodel_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='additional_information',
            field=models.TextField(null=True),
        ),
    ]
