# Generated by Django 3.2.3 on 2022-01-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0021_alter_paymentmodel_payment_ref_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='cogs_value',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
    ]
