# Generated by Django 3.2.3 on 2022-01-12 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0023_alter_contractmodel_factoring_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractmodel',
            name='cogs_value',
        ),
    ]
