# Generated by Django 3.2.3 on 2022-01-12 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0010_auto_20200508_1851'),
        ('transaction_app', '0024_remove_contractmodel_cogs_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinvoicecountrymodel',
            name='destination_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fund_invoice_destination_city', to='cities_light.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundinvoicecountrymodel',
            name='origin_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fund_invoice_origin_city', to='cities_light.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundinvoicecountrymodel',
            name='shipment_mode',
            field=models.PositiveSmallIntegerField(choices=[(1, 'AIR'), (2, 'SEA')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fundinvoicecountrymodel',
            name='destination_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_invoice_destination_country', to='cities_light.country'),
        ),
        migrations.AlterField(
            model_name='fundinvoicecountrymodel',
            name='origin_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_invoice_origin_country', to='cities_light.country'),
        ),
    ]
