# Generated by Django 3.2.3 on 2022-01-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0027_notificationmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationmodel',
            old_name='user_detail',
            new_name='on_boarding_details',
        ),
    ]
