# Generated by Django 3.2.3 on 2022-01-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0029_alter_fundinvoicecountrymodel_shipment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttypemodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
