# Generated by Django 3.2.3 on 2022-02-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0031_auto_20220128_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
