# Generated by Django 3.2.3 on 2022-02-11 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction_app', '0033_notificationmodel_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinvoicemodel',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
