# Generated by Django 3.2.3 on 2022-02-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0034_fundinvoicemodel_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BANK_TRANSFER'), (2, 'LETTER_OF_CREDIT')]),
        ),
    ]
