# Generated by Django 3.2.3 on 2022-02-25 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0035_alter_paymentmodel_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundinvoicemodel',
            name='approved_by',
        ),
    ]
