# Generated by Django 3.2.3 on 2022-02-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0036_remove_fundinvoicemodel_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinvoicemodel',
            name='date_approved',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='signedcontractfilesmodel',
            name='date_modified',
            field=models.DateField(null=True),
        ),
    ]
