# Generated by Django 3.2.3 on 2022-05-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0038_auto_20220225_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
