# Generated by Django 3.2.7 on 2021-10-06 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('email_address', models.EmailField(max_length=200)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_email', models.EmailField(max_length=200)),
                ('company_website', models.URLField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('company_registered_in', django_countries.fields.CountryField(max_length=2)),
                ('annual_revenue', models.CharField(blank=True, default=None, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ADMIN'), (2, 'SME'), (3, 'SUPPLIER'), (4, 'FACTOR')], null=True)),
                ('alternate_email', models.EmailField(blank=True, max_length=200)),
                ('sign_up_email', models.EmailField(blank=True, max_length=200, unique=True)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=50)),
                ('sign_up_phone_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('current_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Lead'), (2, 'Opportunity'), (3, 'Prospect'), (4, 'Rejected'), (5, 'Customer')], null=True)),
                ('submitted_date', models.DateField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LeadStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_created_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Lead'), (2, 'Opportunity'), (3, 'Prospect'), (4, 'Rejected'), (5, 'Customer')], null=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_status_action_by', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_status', to='contact_app.leadsmodel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
