# Generated by Django 3.2.7 on 2021-10-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0002_leadsmodel_invoice_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsmodel',
            name='current_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Lead'), (2, 'Rejected'), (3, 'Customer')], null=True),
        ),
        migrations.AlterField(
            model_name='leadstatusmodel',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Lead'), (2, 'Rejected'), (3, 'Customer')], null=True),
        ),
    ]
