# Generated by Django 3.2.3 on 2021-11-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0003_auto_20211029_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsmodel',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20, null=True),
        ),
    ]
