# Generated by Django 3.2.3 on 2022-05-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0006_leadsmodel_sync_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsmodel',
            name='company_website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
