# Generated by Django 3.2.3 on 2022-05-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0007_alter_leadsmodel_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsmodel',
            name='is_mail_send',
            field=models.BooleanField(default=False),
        ),
    ]
